In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

fullData = pd.read_csv("../final_code/data/weekly_cancer.csv")
#myData = fullData[['Quarter', 'HB', 'CancerType','NumberOfEligibleReferrals31DayStandard','NumberOfEligibleReferralsTreatedWithin31Days']]
HBs=pd.read_csv("../final_code/data/HBs.csv")

fullData.rename(columns={"Cancer type": "CancerType"}, inplace=True)
fullData

# import required modules

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import PoissonRegressor
from matplotlib import pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

import statsmodels.api as sm

popsize = pd.read_csv("PopEstimates.csv")


def find_popsize(HB,Q,popsize):
    Q=str(Q)
    year=Q[0:4]
    #year=np.int(np.floor(Q/100))
    
    x=np.where(popsize['Health Board Code']==HB)
    popsize2=np.asarray(popsize[year])
    return popsize2[x]

In [2]:
# check
HB='S08000015'
Q=201234

find_popsize(HB,Q,popsize)

array([373220])

In [3]:
HB_unique = HBs.drop(HBs.dropna(subset=['HBDateArchived']).index)
HB_unique['HBName'] = HB_unique.HBName.replace({' and ':' & '}, regex=True)
HB_unique

,HB,HBName,HBDateEnacted,HBDateArchived,Country
0,S08000015,NHS Ayrshire & Arran,20140401,NaN,S92000003
1,S08000016,NHS Borders,20140401,NaN,S92000003
2,S08000017,NHS Dumfries & Galloway,20140401,NaN,S92000003
4,S08000019,NHS Forth Valley,20140401,NaN,S92000003
5,S08000020,NHS Grampian,20140401,NaN,S92000003
7,S08000022,NHS Highland,20140401,NaN,S92000003
9,S08000024,NHS Lothian,20140401,NaN,S92000003
10,S08000025,NHS Orkney,20140401,NaN,S92000003
11,S08000026,NHS Shetland,20140401,NaN,S92000003
13,S08000028,NHS Western Isles,20140401,NaN,S92000003
14,S08000029,NHS Fife,20180202,NaN,S92000003
15,S08000030,NHS Tayside,20180202,NaN,S92000003
16,S08000031,NHS Greater Glasgow & Clyde,20190401,NaN,S92000003
17,S08000032,NHS Lanarkshire,20190401,NaN,S92000003

In [4]:
Areas=np.asarray(fullData['Area name'])
HB_code=np.asarray(HB_unique['HB'])
print(HB_code)
HB_name=np.asarray(HB_unique['HBName'])
print(HB_name)

for i in np.arange(len(HB_name)):
    y=np.where(Areas==HB_name[i])
    Areas[y]=HB_code[i]


fullData['HB'] =Areas.tolist()
print(np.unique(fullData['HB']))

['S08000015' 'S08000016' 'S08000017' 'S08000019' 'S08000020' 'S08000022'
 'S08000024' 'S08000025' 'S08000026' 'S08000028' 'S08000029' 'S08000030'
 'S08000031' 'S08000032']
['NHS Ayrshire & Arran' 'NHS Borders' 'NHS Dumfries & Galloway'
 'NHS Forth Valley' 'NHS Grampian' 'NHS Highland' 'NHS Lothian'
 'NHS Orkney' 'NHS Shetland' 'NHS Western Isles' 'NHS Fife' 'NHS Tayside'
 'NHS Greater Glasgow & Clyde' 'NHS Lanarkshire']
['NCA' 'S08000015' 'S08000016' 'S08000017' 'S08000019' 'S08000020'
 'S08000022' 'S08000024' 'S08000025' 'S08000026' 'S08000028' 'S08000029'
 'S08000030' 'S08000031' 'S08000032' 'SCAN' 'Scotland' 'WOSCAN']

In [5]:

Reigons = ['S08000015', 'S08000016', 'S08000017', 'S08000019', 'S08000020', 'S08000022', 'S08000024', 'S08000025', 'S08000026', 'S08000028', 'S08000029', 'S08000030', 'S08000031', 'S08000032']
#Reigons= ['NCA','WOSCAN','SCAN']
  # selecting rows based on condition
# selecting rows based on condition
f=fullData[fullData['Area name'].isin(Reigons)]

#f=fullData

In [6]:


keep_col = ['HB','CancerType','Sex','Age Group', 'Week Number','Count 2019']
cancerdata_2019 = f[keep_col]
cancerdata_2019.rename(columns={"Count 2019": "Count"}, inplace=True)
keep_col = ['HB','CancerType','Sex','Age Group', 'Week Number','Count 2020']
cancerdata_2020 = f[keep_col]

cancerdata_2020.rename(columns={"Count 2020": "Count"}, inplace=True)
keep_col = ['HB','CancerType','Sex','Age Group', 'Week Number','Count 2021']
cancerdata_2021 = f[keep_col]

cancerdata_2021.rename(columns={"Count 2021": "Count"}, inplace=True)

/home/s1657372/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [7]:
np.floor(34/53 *4 )+1

3.0

In [8]:
cancerdata_2020

,HB,CancerType,Sex,Age Group,Week Number,Count
255,S08000015,All Cancers,Male,All Ages,1,3
256,S08000015,All Cancers,Female,All Ages,1,6
257,S08000015,All Cancers,All,All Ages,1,9
258,S08000015,All Malignant Neoplasms (Excl. C44),Male,All Ages,1,1
259,S08000015,All Malignant Neoplasms (Excl. C44),Female,All Ages,1,4
...,...,...,...,...,...,...
671346,S08000030,Leukaemias,Female,All Ages,53,0
671347,S08000028,Hodgkin Lymphoma,Female,All Ages,53,0
671348,S08000028,Pancreas,Male,All Ages,53,0
671349,S08000028,Pancreas,All,All Ages,53,0
671350,S08000028,"Trachea, Bronchus and Lung",Female,All Ages,53,0

In [9]:
def weeknumber_2019(weekn):
    quarters=[]
    months=[]
    weeks=[]
    for wn in weekn:
        if wn in np.arange(6):
            month=1
            week=wn-1
        elif wn in np.arange(6,10):
            month=2
            week=wn-6
        elif wn in np.arange(10,14):
            month=3
            
            week=wn-10
        elif wn in np.arange(14,20):
            month=4
            
            week=wn-14
        elif wn in np.arange(20,24):
            month=5
            
            week=wn-20
        elif wn in np.arange(24,27):
            month=6
            
            week=wn-24
        elif wn in np.arange(27,32):
            month=7
            
            week=wn-27
        elif wn in np.arange(32,36):
            month=8
            
            week=wn-32
        elif wn in np.arange(36,41):
            month=9
            week=wn-36
        elif wn in np.arange(41,45):
            month=10
            week=wn-41
        elif wn in np.arange(45,49):
            month=11
            week=wn-45
        elif wn in np.arange(49,53):
            month=12
            week=wn-49
        weeks.append(week)
        months.append(month)
        quarters.append(np.int(np.floor(month/4)+1))
    return np.asarray(quarters),np.asarray(months),np.asarray(weeks)+1

def weeknumber_2020(weekn):
    quarters=[]
    months=[]
    weeks=[]
    for wn in weekn:
        if wn in np.arange(6):
            week=wn-1
            month=1
        elif wn in np.arange(6,10):
            month=2
            week=wn-6
        elif wn in np.arange(10,15):
            month=3
            week=wn-10
        elif wn in np.arange(15,19):
            month=4
            week=wn-15
        elif wn in np.arange(19,23):
            month=5
            week=wn-19
        elif wn in np.arange(23,28):
            month=6
            week=wn-23
        elif wn in np.arange(28,32):
            month=7
            week=wn-28
        elif wn in np.arange(32,37):
            month=8
            week=wn-32
        elif wn in np.arange(37,41):
            month=9
            week=wn-37
        elif wn in np.arange(41,45):
            month=10
            week=wn-41
        elif wn in np.arange(45,50):
            month=11
            week=wn-45
        elif wn in np.arange(50,54):
            month=12
            week=wn-50
        months.append(month)
        quarters.append(np.int(np.floor(month/4)+1))
        weeks.append(week)
    return np.asarray(quarters),np.asarray(months),np.asarray(weeks)+1

def weeknumber_2021(weekn):
    quarters=[]
    months=[]
    weeks=[]
    for wn in weekn:
        if wn in np.arange(5):
            week=wn-1
            month=1
        elif wn in np.arange(5,9):
            month=2
            week=wn-5
        elif wn in np.arange(9,14):
            month=3
            week=wn-9
        elif wn in np.arange(14,18):
            month=4
            week=wn-14
        elif wn in np.arange(18,23):
            month=5
            week=wn-18
        elif wn in np.arange(23,27):
            month=6
            week=wn-23
        elif wn in np.arange(27,31):
            month=7
            week=wn-27
        elif wn in np.arange(31,36):
            month=8
            week=wn-31
        elif wn in np.arange(36,40):
            month=9
            week=wn-36
        elif wn in np.arange(40,44):
            month=10
            week=wn-40
        elif wn in np.arange(44,49):
            month=11
            week=wn-44
        elif wn in np.arange(49,54):
            month=12
            week=wn-49
        weeks.append(week)
        months.append(month)
        quarters.append(np.int(np.floor(month/4)+1))
    return np.asarray(quarters),np.asarray(months),np.asarray(weeks)+1

In [10]:

quarter,month,week=weeknumber_2019(np.asarray(cancerdata_2019['Week Number']))
date=month*100+20190000+week
month=month+201900
quarter=quarter+201900
cancerdata_2019['Quarter']=quarter.tolist()
cancerdata_2019['Month'] =month.tolist()
cancerdata_2019['Date'] =date.tolist()


quarter,month,week=weeknumber_2020(np.asarray(cancerdata_2020['Week Number']))
date=month*100+20200000+week
month=month+202000
quarter=quarter+202000
cancerdata_2020['Quarter'] =quarter.tolist()
cancerdata_2020['Month'] =month.tolist()
cancerdata_2020['Date'] =date.tolist()

quarter,month,week=weeknumber_2021(np.asarray(cancerdata_2021['Week Number']))
date=month*100+20210000+week
month=month+202100
quarter=quarter+202100
cancerdata_2021['Quarter'] =quarter.tolist()
cancerdata_2021['Month'] =month.tolist()
cancerdata_2021['Date'] =date.tolist()

<ipython-input-10-b2d8dfee5e3a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cancerdata_2019['Quarter']=quarter.tolist()
<ipython-input-10-b2d8dfee5e3a>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cancerdata_2019['Month'] =month.tolist()
<ipython-input-10-b2d8dfee5e3a>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cancerdata_2019['Date'] =date.tolist()
<ipython-input-10-b2d8dfee5e3a>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cancerdata_2020['Quarter'] =quarter.tolist()
<ipython-input-10-b2d8dfee5e3a>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cancerdata_2020['Month'] =month.tolist()
<ipython-input-10-b2d8dfee5e3a>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cancerdata_2020['Date'] =date.tolist()
<ipython-input-10-b2d8dfee5e3a>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cancerdata_2021['Quarter'] =quarter.tolist()
<ipython-input-10-b2d8dfee5e3a>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cancerdata_2021['Month'] =month.tolist()
<ipython-input-10-b2d8dfee5e3a>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cancerdata_2021['Date'] =date.tolist()

In [11]:
all_years=pd.concat([cancerdata_2019,cancerdata_2020,cancerdata_2021],ignore_index=True)

In [12]:
all_years

,HB,CancerType,Sex,Age Group,Week Number,Count,Quarter,Month,Date
0,S08000015,All Cancers,Male,All Ages,1,33.0,201901,201901,20190101
1,S08000015,All Cancers,Female,All Ages,1,22.0,201901,201901,20190101
2,S08000015,All Cancers,All,All Ages,1,55.0,201901,201901,20190101
3,S08000015,All Malignant Neoplasms (Excl. C44),Male,All Ages,1,19.0,201901,201901,20190101
4,S08000015,All Malignant Neoplasms (Excl. C44),Female,All Ages,1,14.0,201901,201901,20190101
...,...,...,...,...,...,...,...,...,...
1527667,S08000030,Leukaemias,Female,All Ages,53,NaN,202104,202112,20211205
1527668,S08000028,Hodgkin Lymphoma,Female,All Ages,53,NaN,202104,202112,20211205
1527669,S08000028,Pancreas,Male,All Ages,53,NaN,202104,202112,20211205
1527670,S08000028,Pancreas,All,All Ages,53,NaN,202104,202112,20211205
1527671,S08000028,"Trachea, Bronchus and Lung",Female,All Ages,53,NaN,202104,202112,20211205

In [19]:
# remove Nans
df=all_years
df = df[df['Count'].notna()]

# remove 'all cancer types' from data
df = df[df['CancerType'] != 'All Cancers']

df = df[df['Sex'] != 'All']
df = df[df['Age Group'] != 'All Ages']


# add a numerical variable 1-1 to date and an index variable before/after pandemic
# and population size
quarters=np.asarray(df['Quarter'])
dates=np.asarray(df['Date'])
months=np.asarray(df['Month'])
HBs=np.asarray(df['HB'])


date=np.zeros(len(dates))
quars=df['Date'].unique()


dates_numerical=np.arange(len(quars))

pop_size=np.zeros(len(dates))

pandemic=np.zeros(len(dates))
pandemic_cat = np.zeros(len(dates))
justpandemic=np.zeros(len(dates))
pandemicRecovery=np.zeros(len(dates))

In [20]:




for i in np.arange(len(dates)):
    Q=quarters[i]
    HB=HBs[i]
    pop_size[i]=find_popsize(HB,Q,popsize)
    y=np.where(quars==dates[i])
    date[i]=dates_numerical[y] # change if we don't want the nuemrical variable to be integers (what is best?)


xs=np.where(months>202003) # change to decide in which quarter the pandemic begins
zs = np.where(months > 202102) # change to decide where recovery from pandemic begins.
pandemic_cat[xs]=pandemic_cat[xs]+1

justpandemic[xs]=date[xs]-date[np.min(xs)]

pandemicRecovery[zs]=date[zs]-date[np.min(zs)]

In [21]:

# save data

df['PopSize'] =pop_size.tolist()
df['Date'] =date.tolist()
df['Pandemic_cat'] = pandemic_cat.tolist()
df['JustPandemic'] =justpandemic.tolist()
df['PandemicRecovery'] =pandemicRecovery.tolist()

df

,HB,CancerType,Sex,Age Group,Week Number,Count,Quarter,Month,Date,PopSize,Pandemic_cat,JustPandemic,PandemicRecovery
28281,S08000015,All Malignant Neoplasms (Excl. C44),Male,0 - 49,1,1.0,201901,201901,0.0,369360.0,0.0,0.0,0.0
28282,S08000015,All Malignant Neoplasms (Excl. C44),Male,50 - 69,1,9.0,201901,201901,0.0,369360.0,0.0,0.0,0.0
28283,S08000015,All Malignant Neoplasms (Excl. C44),Male,70+,1,9.0,201901,201901,0.0,369360.0,0.0,0.0,0.0
28284,S08000015,All Malignant Neoplasms (Excl. C44),Female,0 - 49,1,1.0,201901,201901,0.0,369360.0,0.0,0.0,0.0
28285,S08000015,All Malignant Neoplasms (Excl. C44),Female,50 - 69,1,4.0,201901,201901,0.0,369360.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1126391,S08000028,Hodgkin Lymphoma,Male,70+,24,0.0,202102,202106,128.0,26500.0,1.0,62.0,15.0
1126392,S08000028,Hodgkin Lymphoma,Female,0 - 49,24,1.0,202102,202106,128.0,26500.0,1.0,62.0,15.0
1126395,S08000028,Non-Hodgkin lymphoma,Male,0 - 49,24,0.0,202102,202106,128.0,26500.0,1.0,62.0,15.0
1126397,S08000028,Pancreas,Female,50 - 69,24,0.0,202102,202106,128.0,26500.0,1.0,62.0,15.0
1126398,S08000028,"Trachea, Bronchus and Lung",Female,0 - 49,24,0.0,202102,202106,128.0,26500.0,1.0,62.0,15.0

In [ ]:

# export file
df.to_csv('data/weekdata.csv')